name: Deploy Vulnerable Application

on:
  push:
    branches:
      - main

jobs:
  deploy-heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "vuln-app-jg" # Must be unique in Heroku
          heroku_email: "yoelgoroso@gmail.com"
          remote_branch: "main"
          usedocker: true

  deploy-digitalocean:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: deploy-heroku
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/your-image-name:latest .
          docker push your-dockerhub-username/your-image-name:latest

      - name: SSH to Droplet and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/your-image-name:latest
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d --name your-container-name -p 80:80 your-dockerhub-username/your-image-name:latest
