name: Deploy Vulnerable Application

on:
  push:
    branches:
      - main

jobs:
  deploy-digitalocean:
    name: Deploy to DigitalOcean and Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ilcoyo95/vuln-web-app-jg:latest .
          docker push ilcoyo95/vuln-web-app-jg:latest

      - name: SSH to Droplet and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            docker pull ilcoyo95/vuln-web-app-jg:latest
            docker stop vuln-web-app || true
            docker rm vuln-web-app || true
            docker run -d --name vuln-web-app -p 80:8080 ilcoyo95/vuln-web-app-jg:latest

      - name: Install Snyk CLI
        run: npm install -g snyk
    
      - name: Run Snyk Vulnerability Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --json > snyk-report.json

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-report
          path: snyk-report.json
          
  deploy-heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: deploy-digitalocean
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "vuln-app-jg" # Must be unique in Heroku
          heroku_email: "yoelgoroso@gmail.com"
          remote_branch: "main"
          usedocker: true
